# Tensors Operations

## Basic tensor

In [3]:
import torch

In [5]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Reshape

In [8]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
my_torch_2 = torch.arange(10)
my_torch_2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Automatic Reshape
my_torch_2 = my_torch_2.reshape(-1, 5)
my_torch_2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

## View

In [19]:
my_torch_3 = torch.arange(10)
my_torch_3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# Automatic View
my_torch_4 = my_torch_3.view(2, 5)
my_torch_4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

## Update

In [27]:
my_torch_5 = torch.arange(10)
my_torch_5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
my_torch_6 = my_torch_5.reshape(2, 5)
my_torch_6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [29]:
my_torch_5[1] = 4141
my_torch_5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
# Automatic update
my_torch_6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

## Slices

In [31]:
my_torch_7 = torch.arange(10)
my_torch_7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Grab a specific number
my_torch_7[7]

tensor(7)

In [34]:
# Grab a slice
my_torch_8 = my_torch_7.reshape(5, 2)
my_torch_8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [35]:
my_torch_8[:,1]

tensor([1, 3, 5, 7, 9])

In [36]:
# Return collumn
my_torch_8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])