# Tensor Math Operations

## Addition

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_a
tensor_b = torch.tensor([5, 6, 7, 8])
tensor_b

tensor([5, 6, 7, 8])

In [3]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
# Addition LongHand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

## Subtraction

In [ ]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [7]:
# Sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

## Multiplication

In [8]:
# Mult
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
# Mul LongHand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

## Division

In [ ]:
# Division
tensor_b / tensor_a


tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
# Division LongHand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

## Mod      

In [ ]:
# Remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
# Remainder LongHand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

## Exponents and Power

In [16]:
# Exponents LongHand
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

## Reassignment

In [ ]:
# Reassignment_
tensor_a.add_(tensor_b)
tensor_a    

tensor([21, 26, 31, 36])